# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  test-go:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run: wget https://go.dev/dl/go1.21.4.linux-amd64.tar.gz
      - run: sudo tar -C /usr/local -xzf go1.21.4.linux-amd64.tar.gz
      - run: export PATH=$PATH:/usr/local/go/bin
      - run: mkdir ~/tmp/
      - run: go install gotest.tools/gotestsum@latest
      - run:
          name: Install libseccomp and slirp4netns
          command: sudo apt-get update && sudo apt-get install libseccomp-dev slirp4netns -y
      - run: go mod download
      - run:
          name: Run tests
          command: TMPDIR=~/tmp/ CI_NO_CGROUP=1 gotestsum -f testdox ./...

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  test-go:
    jobs:
      - test-go
