# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  go: circleci/go@1.11.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  test-amd64:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - go/install:
          version: 1.21.4
      - go/load-cache
      - run: mkdir ~/tmp/
      - run: go install gotest.tools/gotestsum@latest
      - run:
          name: Install libseccomp and slirp4netns
          command: DEBIAN_FRONTEND=noninteractive sudo apt-get update && sudo apt-get install libseccomp-dev slirp4netns -y
      - go/mod-download
      - go/save-cache:
          path: /home/circleci/.go_workspace/pkg
      - run:
          name: Run tests
          command: TMPDIR=~/tmp/ CI_NO_CGROUP=1 gotestsum -f testdox ./...

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  integration:
    jobs:
      - test-amd64
